### ISSUE TITLE
installation of slurmdbd in an existing conf of slurm

### ISSUE THREAD

**Issue by potant** [gabrieleiannetti/slurm_cluster_installation#1]
Hello,
firstly congrats for your wiki...
The big question is what if there is an existing running installation of slurm without slurmdbd...
Can slurmdbd be installed now or the whole slurm has to be installed from scratch? Have you ever experienced that?
Thanx in advance

**Comment by gabrieleiannetti** [comment]
Hi,  
sorry for the very late answer!  
Good question, sorry I cannot answer that question...
